{"content": "\nIt starts a try block. If an Exception is thrown inside a try block, the Exception will be compared to any of the catch part of the block. If the Exception matches with one of the Exceptions in the catch part, the exception will be handled there.\n\nThree things can happen in a try block:\n\nNo exception is thrown:\nthe code in the try block\nplus the code in the finally block will be executed\nplus the code after the try-catch block is executed\nAn exception is thrown and a match is found among the catch blocks:\nthe code in the try block until the exception occurred is executed\nplus the matched catch block is executed\nplus the finally block is executed\nplus the code after the try-catch block is executed\nAn exception is thrown and no match found among the catch blocks:\nthe code in the try block until the exception occurred is executed\nplus the finally block is executed\nNO CODE after the try-catch block is executed\n\n\n\n\n\npublic void method() throws NoMatchedException\n {\n   try {\n     //...\n     throw new '''MyException_1'''();\n     //...\n   } catch ( MyException_1 e ) {\n     // --- '''Handle the Exception_1 here''' --\n   } catch ( MyException_2 e ) {\n     // --- Handle the Exception_2 here --\n   } finally {\n     // --- This will always be executed no matter what --\n   }\n   // --- Code after the try-catch block\n }\n\n\nHow the catch-blocks are evaluated see Catching Rule\n\nJava Programming/Keywords/catch\nJava Programming/Keywords/finally\nJava Programming/Throwing and Catching Exceptions#Catching Rule", "heading": "try"}